server:
    port: 8080
    servlet:
        context-path: /

app:
    base_url: http://localhost:8080

spring:
    application:
        name: Test
    datasource:
        url: ${spring.jpa.hibernate.connection.url}
        driver-class-name: ${spring.jpa.hibernate.connection.driver-class-name}
        username: ${spring.jpa.hibernate.connection.username}
        password: ${spring.jpa.hibernate.connection.password}
    jpa:
        hibernate:
            connection:
                url: jdbc:postgresql://127.0.0.1:5432/multi_tenant_V1?ApplicationName=Test
                username: postgres
                password: 1234
                driver-class-name: org.postgresql.Driver
            ddl-auto: none
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    flyway:
        baseline-on-migrate: true
        enabled: false
        baseline-description: "init"
        baseline-version: 0
        url: ${spring.jpa.hibernate.connection.url}
        user: ${spring.jpa.hibernate.connection.username}
        password: ${spring.jpa.hibernate.connection.password}
        driver-class-name:  ${spring.jpa.hibernate.connection.driver-class-name}
    main:
        allow-circular-references: true


